### PR TITLE
Add support for multiple extensions

### LINKED ISSUE #6: Highlighting is messed up as soon as I add attributes
The syntax highlighting in Sublime is messed up as soon as I add attributes:

image

### PR DESCRIPTION
**Pull request by torkleyy**
Fixes #6

Untested, someone who uses Sublime please confirm it works

### CODE REVIEW

**Comment by entropylost** [comment]
It didn't work even with one extension...

**Comment by torkleyy** [comment]
I don't think this is fully correct regarding all the meta scopes, but this gives me working highlighting with one or multiple extensions in a ron file.

image

**Comment by entropylost** [comment]
Published?

**Comment by torkleyy** [comment]
Yes, but I don't know how long it takes for Sublime to pick up the new version.

**Pull request merged**
